repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2  # Версия Ruff
    hooks:
      - id: ruff
        name: Run Code-Style Checks
        args: [ --no-cache ]
        always_run: true

  - repo: local
    hooks:
      - id: pytest
        name: Run Tests
        language: system
        entry: python -m pytest
        pass_filenames: false
        always_run: true
